-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQwV/hnYcWNvOnarC
xih/oQx8o9mVYa7/jKN+9UNjg2OgCgYIKoZIzj0DAQehRANCAASccHGBaxmZZYTq
Yh60tHS7JcM0p8qpCfWgn0bzhmdl66u/AyhO6A/tDMOb2nNgjviATBbUZA2adbta
DTrDGfwt
-----END PRIVATE KEY-----